import { useEffect, useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { MapPin, Wifi, Shield, DollarSign, Bookmark, RotateCcw, Share2, AlertTriangle, Zap, Globe, Clock } from 'lucide-react';
import { City } from '@/data/cities';
import { Button } from '@/components/ui/button';
import HealthBar from '@/components/HealthBar';
import DeploymentGrid from '@/components/DeploymentGrid';
import { generateAffiliateLinks } from '@/utils/affiliateEngine';
import { trackSpinCompleted } from '@/utils/analytics';
import confetti from 'canvas-confetti';

interface ResultCardProps {
  city: City;
  matchScore: number;
  intel: string[];
  risks: string[];
  originCity?: string;
  onSave: () => void;
  onRespin: () => void;
  onShare: () => void;
}

function AnimatedScore({ target }: { target: number }) {
  const [value, setValue] = useState(0);
  const rafRef = useRef<number>(0);

  useEffect(() => {
    const start = performance.now();
    const duration = 1200;
    const animate = (now: number) => {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setValue(Math.round(eased * target));
      if (progress < 1) rafRef.current = requestAnimationFrame(animate);
    };
    const timeout = setTimeout(() => {
      rafRef.current = requestAnimationFrame(animate);
    }, 600);
    return () => { clearTimeout(timeout); cancelAnimationFrame(rafRef.current); };
  }, [target]);

  return <span>{value}</span>;
}

function ScoreRing({ score }: { score: number }) {
  const circumference = 2 * Math.PI * 42;
  const offset = circumference - (score / 100) * circumference;

  return (
    <div className="relative w-20 h-20 flex-shrink-0">
      <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
        <circle cx="50" cy="50" r="42" fill="none" stroke="hsl(var(--border))" strokeWidth="1" />
        <motion.circle
          cx="50" cy="50" r="42"
          fill="none"
          stroke="hsl(var(--foreground))"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeDasharray={circumference}
          initial={{ strokeDashoffset: circumference }}
          animate={{ strokeDashoffset: offset }}
          transition={{ duration: 2, ease: 'easeOut', delay: 0.6 }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-lg font-mono font-light text-foreground tracking-wider">
          <AnimatedScore target={score} />
        </span>
        <span className="text-[8px] font-mono text-muted-foreground uppercase tracking-[0.2em]">match</span>
      </div>
    </div>
  );
}

export default function ResultCard({ city, matchScore, intel, risks, originCity, onSave, onRespin, onShare }: ResultCardProps) {
  const affiliateLinks = generateAffiliateLinks(city, originCity);

  useEffect(() => {
    trackSpinCompleted(city.name, city.country, matchScore, city.region);

    const timer = setTimeout(() => {
      confetti({
        particleCount: 60,
        spread: 80,
        origin: { y: 0.6 },
        colors: ['#ffffff', '#4488ff', '#888888'],
        gravity: 1.2,
        ticks: 120,
      });
    }, 500);
    return () => clearTimeout(timer);
  }, [city.id, matchScore]);

  // Affiliate URLs are now generated by affiliateEngine

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
      className="w-full max-w-lg mx-auto overflow-hidden"
    >
      <div className="gradient-border-wrap rounded-sm">
        <div className="bg-black/80 backdrop-blur-[60px] rounded-sm">

          {/* Header: City + Score */}
          <div className="p-6 pb-4">
            <div className="flex items-start gap-4">
              <ScoreRing score={matchScore} />
              <div className="flex-1 min-w-0 pt-1">
                <motion.h2
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.4, duration: 0.6 }}
                  className="text-2xl md:text-3xl font-mono font-light tracking-[0.15em] text-foreground truncate uppercase"
                >
                  {city.name} <span className="text-muted-foreground">// {city.countryCode}</span>
                </motion.h2>
                <div className="flex items-center gap-2 text-muted-foreground mt-1">
                  <MapPin className="w-3 h-3" />
                  <span className="text-[10px] font-mono tracking-wider">{city.country} · {city.region}</span>
                  <span className="text-[10px] font-mono tracking-wider text-muted-foreground/60">{city.meta.timeZoneUtc}</span>
                </div>
                <div className="flex flex-wrap gap-1.5 mt-2">
                  {city.vibe.map((v) => (
                    <span key={v} className="px-2 py-0.5 text-[9px] font-mono tracking-wider rounded-sm border border-border text-muted-foreground uppercase">
                      {v}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Tactical Data Grid */}
          <div className="grid grid-cols-2 gap-px bg-border/20 mx-6">
            <StatItem icon={<DollarSign className="w-3 h-3" />} label="EST. MONTHLY BURN" value={`$${city.financials.costNomadSingle.toLocaleString()}`} />
            <StatItem icon={<Wifi className="w-3 h-3" />} label="AVG BANDWIDTH" value={`${city.infra.internetSpeedAvg} Mbps`} />
            <StatItem icon={<Shield className="w-3 h-3" />} label="THREAT INDEX" value={`${city.safety}/10`} />
            <StatItem icon={<Globe className="w-3 h-3" />} label="VISA WINDOW" value={`${city.meta.visaDays}D`} />
            <StatItem icon={<Globe className="w-3 h-3" />} label="AIRBNB MEDIAN" value={`$${city.financials.airbnbMedian}/NT`} />
            <StatItem icon={<Clock className="w-3 h-3" />} label="LONG-TERM COST" value={`$${city.financials.costLongTerm.toLocaleString()}`} />
          </div>

          {/* Health Bars */}
          <div className="px-6 py-4 space-y-2.5">
            <HealthBar label="BANDWIDTH" value={city.infra.internetReliability} delay={0.8} />
            <HealthBar label="SAFETY" value={Math.round(city.safety)} delay={0.9} />
            <HealthBar label="NIGHTLIFE" value={city.vibeMetrics.nightlife} delay={1.0} />
            <HealthBar label="COMMUNITY" value={city.vibeMetrics.communitySize} delay={1.1} />
            <HealthBar label="POWER GRID" value={city.infra.powerGridStability} delay={1.2} />
          </div>

          {/* Intel + Risks */}
          <div className="px-6 py-4 grid grid-cols-2 gap-4 border-t border-border/30">
            {/* Intel */}
            <div>
              <div className="flex items-center gap-1.5 text-[9px] font-mono tracking-[0.2em] text-muted-foreground mb-2 uppercase">
                <Zap className="w-3 h-3" /> WHY THIS TARGET
              </div>
              {intel.map((item, i) => (
                <motion.p
                  key={i}
                  initial={{ opacity: 0, x: -5 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 1.2 + i * 0.1 }}
                  className="text-[11px] text-foreground/60 mb-1.5 font-mono leading-relaxed"
                >
                  + {item}
                </motion.p>
              ))}
            </div>
            {/* Risks */}
            <div>
              <div className="flex items-center gap-1.5 text-[9px] font-mono tracking-[0.2em] text-muted-foreground mb-2 uppercase">
                <AlertTriangle className="w-3 h-3" /> OPERATIONAL RISKS
              </div>
              {risks.length > 0 ? risks.map((risk, i) => (
                <motion.p
                  key={i}
                  initial={{ opacity: 0, x: -5 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 1.4 + i * 0.1 }}
                  className="text-[11px] text-destructive/70 mb-1.5 font-mono leading-relaxed"
                >
                  ⚠ {risk}
                </motion.p>
              )) : (
                <p className="text-[11px] text-foreground/40 font-mono">No active threats</p>
              )}
            </div>
          </div>

          {/* Deployment Grid — Affiliate Engine */}
          <div className="px-6 py-3 border-t border-border/30">
            <DeploymentGrid links={affiliateLinks} cityName={city.name} />
          </div>

          {/* Action Row */}
          <div className="px-6 py-4 border-t border-border/30 flex gap-2">
            <Button onClick={onSave} variant="outline" className="flex-1 gap-2 rounded-sm border-border text-foreground/60 hover:bg-white/5 hover:text-foreground text-[10px] font-mono tracking-[0.15em]">
              <Bookmark className="w-3 h-3" /> ENCRYPT TO PROFILE
            </Button>
            <Button onClick={onRespin} variant="outline" className="flex-1 gap-2 rounded-sm border-border text-foreground/60 hover:bg-white/5 hover:text-foreground text-[10px] font-mono tracking-[0.15em]">
              <RotateCcw className="w-3 h-3" /> RE-DROP
            </Button>
            <Button onClick={onShare} variant="outline" className="gap-2 rounded-sm border-border text-foreground/60 hover:bg-white/5 hover:text-foreground text-[10px] font-mono tracking-[0.15em]">
              <Share2 className="w-3 h-3" />
            </Button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function StatItem({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="flex items-center gap-2 p-3 bg-white/[0.02]">
      <span className="text-muted-foreground">{icon}</span>
      <div className="min-w-0">
        <p className="text-[8px] font-mono text-muted-foreground tracking-[0.15em] truncate">{label}</p>
        <p className="text-sm font-mono font-light text-foreground">{value}</p>
      </div>
    </div>
  );
}

