import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Provide __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import our guides data (importing directly from TS source!)
import { guides } from '../src/data/guides';

const distDir = path.resolve(__dirname, '../dist');
const indexHtmlPath = path.join(distDir, 'index.html');

console.log('🚀 Starting Post-Build SEO HTML Generation...');

// Make sure index.html exists in dist
if (!fs.existsSync(indexHtmlPath)) {
  console.error('❌ Error: dist/index.html not found. Please run this after vite build.');
  process.exit(1);
}

const baseHtml = fs.readFileSync(indexHtmlPath, 'utf-8');

// --- Helper Functions ---

/**
 * Creates folders and writes the targeted HTML file.
 */
function createHtmlFile(route: string, title: string, description: string, filename: string = 'index.html') {
  const targetDir = path.join(distDir, route);
  
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // Inject our custom SEO tags by replacing the default title and description
  let customHtml = baseHtml
    // Replace default title
    .replace(
      /<title>.*<\/title>/,
      `<title>${title}</title>`
    )
    // Replace default meta description
    .replace(
      /<meta\s+name="description"\s+content="[^"]*"\s*\/>/,
      `<meta name="description" content="${description}" />`
    )
    // Replace Open Graph title
    .replace(
      /<meta\s+property="og:title"\s+content="[^"]*"\s*\/>/,
      `<meta property="og:title" content="${title}" />`
    )
    // Replace Open Graph description
    .replace(
      /<meta\s+property="og:description"\s+content="[^"]*"\s*\/>/,
      `<meta property="og:description" content="${description}" />`
    )
    // Replace Twitter title
    .replace(
      /<meta\s+name="twitter:title"\s+content="[^"]*"\s*\/>/,
      `<meta name="twitter:title" content="${title}" />`
    )
    // Replace Twitter description
    .replace(
      /<meta\s+name="twitter:description"\s+content="[^"]*"\s*\/>/,
      `<meta name="twitter:description" content="${description}" />`
    );

  const outPath = path.join(targetDir, filename);
  fs.writeFileSync(outPath, customHtml);
  console.log(`✅ Generated: /${route === '' ? filename : route + '/' + filename}`);
}


// --- 1. SPA Fallback for GitHub Pages ---
// Copy the main index.html to 404.html to handle client-side routes gracefully
fs.copyFileSync(indexHtmlPath, path.join(distDir, '404.html'));
console.log('✅ Generated SPA fallback: /404.html');

// --- 2. Generate Static Core Pages ---
// Note: We don't overwrite the root index.html, it's already generated by Vite.
createHtmlFile('about', 'About Us – Nomad Spin', 'Learn about Nomad Spin and how we help digital nomads find their perfect base.');
createHtmlFile('guides', 'Digital Nomad Guides & Analysis – Nomad Spin', 'Read our curated guides, tax analyses, and deep dives for digital nomads and remote workers.');
createHtmlFile('contact', 'Contact Us – Nomad Spin', 'Get in touch with the Nomad Spin team.');
createHtmlFile('privacy-policy', 'Privacy Policy – Nomad Spin', 'Read our privacy policy and how we protect your data.');
createHtmlFile('terms-of-use', 'Terms of Use – Nomad Spin', 'Read our terms of service.');

// --- 3. Generate Static Guide Pages ---
console.log(`\n📚 Generating ${guides.length} guide pages...`);
guides.forEach((guide) => {
  const route = `guides/${guide.slug}`;
  // We use the exact title and excerpt from the content system
  createHtmlFile(route, `${guide.title} – Nomad Spin Guides`, guide.excerpt);
});

// --- 4. Generate Sitemap.xml ---
console.log('\n🗺️ Generating sitemap.xml...');

const today = new Date().toISOString().split('T')[0];
const baseUrl = 'https://digitalnomadspin.com';

let sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${baseUrl}/</loc>
    <lastmod>${today}</lastmod>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${baseUrl}/guides</loc>
    <lastmod>${today}</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>${baseUrl}/about</loc>
    <lastmod>${today}</lastmod>
    <priority>0.8</priority>
  </url>
`;

// Add guides to sitemap
guides.forEach((guide) => {
  sitemapXml += `  <url>
    <loc>${baseUrl}/guides/${guide.slug}</loc>
    <lastmod>${guide.date}</lastmod>
    <priority>0.8</priority>
  </url>\n`;
});

sitemapXml += `</urlset>`;

fs.writeFileSync(path.join(distDir, 'sitemap.xml'), sitemapXml);
console.log('✅ Generated: /sitemap.xml');

console.log('\n✨ Post-Build Generation Complete!');
