/**
 * Compiles editorial guides in content/guides/<slug>.{md,json} into
 * src/data/contentGuides.generated.ts so the app, sitemap and prerender
 * scripts all share one source of truth with the hand-written guides in
 * src/data/guides.ts.
 *
 * Only guides whose JSON has "status": "published" are emitted.
 * Run automatically in predev/prebuild; run manually with:
 *   npx tsx scripts/sync-content-guides.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTENT_DIR = path.resolve(__dirname, '../content/guides');
const OUT_FILE = path.resolve(__dirname, '../src/data/contentGuides.generated.ts');

interface GuideMeta {
  slug: string;
  title: string;
  status: string;
  published?: string;
  last_updated?: string;
  related_destinations?: string[];
  seo?: { meta_title?: string; meta_description?: string };
}

function plainText(md: string): string {
  return md
    .replace(/<[^>]+>/g, ' ')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[#*`_~>|-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function readTime(md: string): string {
  const words = plainText(md).split(' ').filter(Boolean).length;
  return `${Math.max(1, Math.round(words / 200))} min read`;
}

function excerpt(md: string): string {
  const firstPara = md
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .find((p) => p && !p.startsWith('#') && !p.startsWith('>') && !p.startsWith('|'));
  const text = plainText(firstPara ?? md);
  return text.length <= 160 ? text : `${text.slice(0, 157).replace(/\s+\S*$/, '')}…`;
}

/** Escape a string for safe inclusion inside a JS template literal. */
function toTemplateLiteral(s: string): string {
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

export function buildContentGuidesModule(): { source: string; count: number } {
  const files = fs.existsSync(CONTENT_DIR)
    ? fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith('.json')).sort()
    : [];

  const entries: string[] = [];
  for (const file of files) {
    const meta = JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, file), 'utf-8')) as GuideMeta;
    if (meta.status !== 'published') continue;
    const mdPath = path.join(CONTENT_DIR, file.replace(/\.json$/, '.md'));
    if (!fs.existsSync(mdPath)) throw new Error(`Missing markdown for ${file}`);
    const slug = meta.slug || file.replace(/\.json$/, '');
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`Invalid guide slug "${slug}" in ${file}`);

    // The article page renders the title as <h1>; drop a leading markdown H1 to avoid duplicates.
    const md = fs.readFileSync(mdPath, 'utf-8').replace(/^\uFEFF?#\s[^\n]*\n+/, '').trim() + '\n';

    entries.push(`  {
    id: ${JSON.stringify(slug)},
    slug: ${JSON.stringify(slug)},
    title: ${JSON.stringify(meta.title)},
    seoTitle: ${JSON.stringify(meta.seo?.meta_title ?? meta.title)},
    excerpt: ${JSON.stringify(meta.seo?.meta_description ?? excerpt(md))},
    date: ${JSON.stringify(meta.published ?? meta.last_updated ?? '')},
    updated: ${JSON.stringify(meta.last_updated ?? meta.published ?? '')},
    readTime: ${JSON.stringify(readTime(md))},
    relatedDestinations: ${JSON.stringify(meta.related_destinations ?? [])},
    content: ${toTemplateLiteral(md)},
  }`);
  }

  const source = `// AUTO-GENERATED by scripts/sync-content-guides.ts — do not edit by hand.
// Edit content/guides/<slug>.md and .json instead.
import type { Guide } from './guides';

export const contentGuides: Guide[] = [
${entries.join(',\n')}
];
`;
  return { source, count: entries.length };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === __filename;
if (isMain) {
  const { source, count } = buildContentGuidesModule();
  const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, 'utf-8') : '';
  if (prev !== source) {
    fs.writeFileSync(OUT_FILE, source);
    console.log(`contentGuides.generated.ts written (${count} published guide(s))`);
  } else {
    console.log(`contentGuides.generated.ts up to date (${count} published guide(s))`);
  }
}
