// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-cities.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { cities } from "npm:@/data/cities";
var search_cities_default = defineTool({
  name: "search_cities",
  title: "Search nomad cities",
  description: "Search the Digital Nomad Spin city database by name, country, region, or vibe tag. Returns matching cities with key stats.",
  inputSchema: {
    query: z.string().optional().describe("Free-text match on city name, country, or vibe tag."),
    region: z.enum(["Asia", "Europe", "LATAM", "Africa", "Oceania", "North America"]).optional().describe("Filter by region."),
    maxCostUSD: z.number().positive().optional().describe("Max monthly cost in USD."),
    minSafety: z.number().min(0).max(10).optional().describe("Minimum safety rating (0-10)."),
    minInternetMbps: z.number().min(0).optional().describe("Minimum internet speed in Mbps."),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, region, maxCostUSD, minSafety, minInternetMbps, limit }) => {
    const q = query?.toLowerCase().trim();
    const matches = cities.filter((c) => {
      if (region && c.region !== region) return false;
      if (maxCostUSD != null && c.costUSD > maxCostUSD) return false;
      if (minSafety != null && c.safety < minSafety) return false;
      if (minInternetMbps != null && c.internetMbps < minInternetMbps) return false;
      if (!q) return true;
      return c.name.toLowerCase().includes(q) || c.country.toLowerCase().includes(q) || c.vibe.some((v) => v.toLowerCase().includes(q));
    }).slice(0, limit).map((c) => ({
      id: c.id,
      name: c.name,
      country: c.country,
      region: c.region,
      costUSD: c.costUSD,
      safety: c.safety,
      internetMbps: c.internetMbps,
      vibe: c.vibe,
      visa: c.visa
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: matches.length, matches }, null, 2) }],
      structuredContent: { count: matches.length, matches }
    };
  }
});

// src/lib/mcp/tools/get-city.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { cities as cities2 } from "npm:@/data/cities";
var get_city_default = defineTool2({
  name: "get_city",
  title: "Get city details",
  description: "Fetch the full destination profile (financials, infra, weather, visa, taxation, pros/cons) for one city by id or name.",
  inputSchema: {
    idOrName: z2.string().min(1).describe("City id (e.g. 'lisbon') or display name (e.g. 'Lisbon').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ idOrName }) => {
    const needle = idOrName.toLowerCase().trim();
    const city = cities2.find(
      (c) => c.id.toLowerCase() === needle || c.name.toLowerCase() === needle
    );
    if (!city) {
      return {
        content: [{ type: "text", text: `No city found for "${idOrName}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(city, null, 2) }],
      structuredContent: { city }
    };
  }
});

// src/lib/mcp/tools/spin-destination.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { cities as cities3 } from "npm:@/data/cities";
import { calculateMatchScore, generateIntel } from "npm:@/lib/scoring";
var spin_destination_default = defineTool3({
  name: "spin_destination",
  title: "Spin for a destination",
  description: "Run the Nomad Spin scoring engine and return the top matching destinations for the given preferences.",
  inputSchema: {
    maxBudgetUSD: z3.number().positive().default(2e3).describe("Max monthly cost in USD."),
    minInternetMbps: z3.number().min(0).default(30).describe("Minimum internet speed in Mbps."),
    minSafety: z3.number().min(0).max(10).default(6).describe("Minimum safety rating (0-10)."),
    region: z3.enum(["Asia", "Europe", "LATAM", "Africa", "Oceania", "North America"]).optional(),
    topN: z3.number().int().min(1).max(10).default(3)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: ({ maxBudgetUSD, minInternetMbps, minSafety, region, topN }) => {
    const pool = cities3.filter((c) => {
      if (region && c.region !== region) return false;
      return c.costUSD <= maxBudgetUSD && c.internetMbps >= minInternetMbps && c.safety >= minSafety;
    });
    const ranked = pool.map((c) => ({
      city: c,
      score: calculateMatchScore(c, maxBudgetUSD, minInternetMbps, minSafety, null)
    })).sort((a, b) => b.score - a.score).slice(0, topN).map(({ city, score }) => ({
      id: city.id,
      name: city.name,
      country: city.country,
      region: city.region,
      costUSD: city.costUSD,
      internetMbps: city.internetMbps,
      safety: city.safety,
      matchScore: score,
      intel: generateIntel(city, maxBudgetUSD, minInternetMbps, null)
    }));
    const text = ranked.length ? `Top ${ranked.length} destinations:
${ranked.map((r, i) => `${i + 1}. ${r.name}, ${r.country} \u2014 $${r.costUSD}/mo, ${r.internetMbps} Mbps, safety ${r.safety}/10 (score ${r.matchScore})`).join("\n")}` : "No cities matched those preferences. Try relaxing budget, internet, or safety.";
    return {
      content: [{ type: "text", text }],
      structuredContent: { results: ranked }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nomad-spin-mcp",
  title: "Digital Nomad Spin",
  version: "0.1.0",
  instructions: "Tools for the Digital Nomad Spin app. Use `search_cities` to filter the 1,200+ city database, `get_city` for a full destination profile, and `spin_destination` to run the match-scoring engine against a nomad's budget, internet, and safety preferences.",
  tools: [search_cities_default, get_city_default, spin_destination_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
